version: "3.8"

services:
  backend:
    container_name: nextflow-backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - PORT=4000
      - NODE_ENV=production
    restart: always
